### PR TITLE
LXDUI Remote server terminal fix

### PR DESCRIPTION
**Pull request by ye-yng**
This is a fix for PR [252](https://github.com/AdaptiveScale/lxdui/pull/252) in which remote LXD server access was introduced but console access to the remote's instances was broken. To correctly access the console of a remote instance we must input the remote name at `lxdui.lxd.remote.name` inside `__metadata__.py` so it matches the name of the added remote LXD server.

### CODE REVIEW

**Comment by vhajdari** [comment]
Hi Ye,

Are you open to doing a release with all the PRs you've created?

**Comment by ye-yng** [comment]
What would a release entail? I had a previous PR that had all the modifications done in the new PRs so I seperated it into multiple parts so it would be easier to clearly see what was changed. I am however using and developing sepcifically from PR [252](https://github.com/AdaptiveScale/lxdui/pull/252) since I needed to have remote LXD server access.

**Comment by vhajdari** [comment]
A release entails merging the develop branch into master, and cherry
picking some of the other PRs that have been made since the last release.
One of the PRs that would be great to have is related to Snap app support,
so that LXDUI can be set up with a simple Snap install.

**Comment by ye-yng** [comment]
I am open to doing a release, however I can't say much regarding Snap support as I have not looked into it. I have also added a columns to the container page that show's the CPU cores / total memory allocated to each instances, if of interest I can issue a PR with the addition.

**Comment by ye-yng** [comment]
Hi, are there are any guidelines for doing a release?

**Comment by vhajdari** [comment]
Hi Ye,

Please join me on the Slack channel and I can go over it with you ...
lxdui.slack.com

**Comment by ye-yng** [comment]
I need an invite to join your channel.

**Comment by stiltr** [comment]
I'd also love to see a new release for this project. I'm happy to join the slack channel as well if I can help facilitate anything.

**Comment by vhajdari** [comment]
Please use the following invite to join our Slack channel -->
https://join.slack.com/t/lxdui/shared_invite/zt-p63rldl2-G8I8B0iQoWi1x5vuFUDW0A

Regards,

Tony

**Comment by vhajdari** [comment]
Please use the following invite to join our Slack channel -->
https://join.slack.com/t/lxdui/shared_invite/zt-p63rldl2-G8I8B0iQoWi1x5vuFUDW0A

Regards,

Tony

**Pull request merged**
