### PR TITLE
show list of ip addresses with CIDR netmask for network interfaces

### PR DESCRIPTION
**Pull request by felix-engelmann**
The existing display did not show all available IPs for an interface. Now it differentiates between IPv4 and IPv6 and shows the netmasklen in CIDR notation. /24 was expanded to 255.255.255.0 which is wrong for IPv6 /24 addresses.
The Stats were shifted to the next row, because IPv6 addresses are normally quite long.

### CODE REVIEW

**Review by vhajdari — CHANGES_REQUESTED** [review]
Hi @felix-engelmann, thanks for the PR.  The Python changes LGTM, but on the UI I propose the following look and feel:
image

**Comment by vhajdari** [comment]
this is what the UI change looks like--
image

Compared to the original--
image

Let's cherry pick the python changes but for the UI I propose we add an IPv6 icon that would be enabled if the interface has an IPv6 address it would show a tooltip with the IPv6 and netmask on hover-- kinda what we had in version 1.0
We can add the netmask after the IP address (10.2.3.4 / 24) with the netmask portion wrapped in a bubble that will display the netmask on hover--just like the previous item.

**Comment by felix-engelmann** [comment]
Hi, I'm no longer using lxdui as I need user and cluster support and have no spare time. Feel free to cherry pick stuff from my PR. I decided to roll my own https://github.com/lxd-manager

**Comment by ye-yng** [comment]
I've  been using this PR as I have LXDUI installed inside a container that contacts my host that I added as a remote on lxc. I noticed that you can't access the terminal as in `terminal.py` under the `NewTerminalHandler` handler class, the console is accessed with `lxc exec {} -- /bin/{}` instead it should be `lxc exec REMOTE_NAME:{} -- /bin/{}` if LXDUI is being used for remote access to a host machine.

**Pull request merged**
