### PR TITLE
Enable limits.cpu setting on container creation menu

### PR DESCRIPTION
**Pull request by ye-yng**
To ease operations I have added a way to set the `limits.cpu` configuration through the main instance creation section instead of it being hidden under `Additional Settings`.

This option is disabled by default and to enable we simply have to set `lxdui.set_limits_cpu` in `__metadata__.py` to `true`.

The interface looks like the following with the option set to `true`:

image

### CODE REVIEW

**Comment by jetroni** [comment]
https://github.com/AdaptiveScale/lxdui/blob/e786ccfdda40ef645f9a4955789014d4ddae7efb/app/ui/blueprint.py#L69
Why is this line needed?

**Comment by ye-yng** [comment]
It is used to set the CPU count limiting interface.

https://github.com/AdaptiveScale/lxdui/blob/e786ccfdda40ef645f9a4955789014d4ddae7efb/app/ui/templates/containers.html#L210

By default it is set to `false`

https://github.com/AdaptiveScale/lxdui/blob/e786ccfdda40ef645f9a4955789014d4ddae7efb/app/__metadata__.py#L48

This means that the default behavior is to allow setting the CPU allowance instead.

**Comment by jetroni** [comment]
https://github.com/AdaptiveScale/lxdui/blob/e786ccfdda40ef645f9a4955789014d4ddae7efb/app/ui/blueprint.py#L66-L69
I think you have two parameters for the same purpose(?), one of them should be removed in my opinion.

**Comment by ye-yng** [comment]
You're right, extra line has been removed.

**Review by jetroni — APPROVED** [review]

**Comment by jetroni** [comment]
Thank you.

**Pull request merged**
