### PR TITLE
Secure UI

### LINKED ISSUE #253: Login form and disabled JavaScript
Go to login page 
Disable JavaScript 
Enter any text as username and password 
Access Granted

tested on LXDUI v2.1.2

### PR DESCRIPTION
**Pull request by stiltr**
Fixes #253.

Migrates from flask_jwt to flask_jwt_extended which seems to be more actively maintained and includes support for jwt tokens in browser cookies. Cookies are used to provide authentication on the UI side and token errors result in a error page that redirects to the login page.

Full disclosure, I'm not a python guy and I've never used flask. I'm sure there are better ways to do things, but my hope is that this at least provides a place to start from. I'm happy to make whatever edits are necessary to make this PR acceptable.

### CODE REVIEW

**Comment by vhajdari** [comment]
Hi @stiltr 
Thanks for the PR.  As soon as @ailegion gets some bandwidth to look at the PR he'll update the ticket with his comments.

**Comment by stiltr** [comment]
Thanks @vhajdari! Looking forward to it.

**Comment by ailegion** [comment]
Hi @stiltr ,
Thanks for the PR, can please re-create it on develop branch so I can merge it there.

**Comment by stiltr** [comment]
Hi @ailegion ,

I'll pull in the dev branch and make the changes and then point this PR at the dev branch as well. Probably should have started on the dev branch, but I didn't initially intend to make any changes. = )

**Comment by stiltr** [comment]
@ailegion 

You should be able to merge it into develop now. I took a quick look over the new content and applied the fixes, but I may have missed something. Let me know.

**Comment by vhajdari** [comment]
@ailegion can you please take at this PR?  There are 2 conflicts that need to be resolved.

**Comment by ailegion** [comment]
@vhajdari @stiltr there few small issues that might require fixing but considering that it solves some of the security issues and uses clearer than we currently have I'm going to go ahead and merge it

**Pull request merged**
